env: vm
base_domain: "{{ env }}.openconext.org"

mysql_host: localhost
rsyslog_host: localhost

database_clients: [ "{{ mysql_host }}" ]

mysql_root_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_77962 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"

mysql_passwords:
  teams: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_20427 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
  eb: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_67388 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
  pdp_server: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_2240 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
  aa_server: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_86908 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
  spdashboard: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_48884 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
  shibboleth: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_84230 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
  lifecycle: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_76277 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"

mongo_passwords:
   manage: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_2073 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
   oidcng: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_92663 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
   myconext: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_81935 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"

mongo_admin_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_33452 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"

engine_parameters_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_73114 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"

profile_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_74379 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"

teams_authz_client_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_60088 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
teams_migration_secret_key: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_75458 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"

engine_api_metadata_push_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_88367 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
oidcng_api_metadata_push_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_18121 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
oidcng_api_tokens_profile_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_6523 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
oidcng_api_tokens_eduid_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_19313 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
myconext_api_attribute_manipulation_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_33079 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
myconext_oidcng_rs_client_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_45445 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
myconext_api_attribute_aggregation_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_71306 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
myconext_client_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_88806 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
myconext_rs_client_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_82296 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
engine_api_profile_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_18980 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
engine_api_deprovision_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_79081 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"

voot_oidcng_checkToken_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_43989 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"

external_group_provider_secrets:
  teams: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_79899 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"

teams_api_lifecycle_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_22207 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
attribute_aggregator_api_lifecycle_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_60445 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"

oidc_playground_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_74727 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
oidc_playground_jwt_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_80621 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
oidc_playground_resource_server_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_97157 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"

pdp_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_86524 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
pdp_client_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_51792 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
pdp_sab_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_10963 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"

aa_eb_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_72239 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
aa_authz_client_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_83983 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
aa_sab_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_72983 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
aa_idin_client_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_30053 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
aa_orcid_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_7530 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
aa_surfmarket_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_52580 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
aa_sbs_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_89492 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
aa_ala_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_19372 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
aa_manage_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_55607 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"

manage_pdp_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_49139 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"

attribute_aggregator_js_access_token: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_28552 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
pdp_js_access_token: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_3916 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"

https_star_private_key: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_32343 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"

mujina_idp_private_key: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_86502 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
mujina_idp_passphrase: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_38415 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
mujina_sp_private_key: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_75126 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
mujina_sp_passphrase: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_42060 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"

manage_internal_api_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_6495 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
manage_backdoor_api_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_7665 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
manage_dashboard_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_61908 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
manage_pdp_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_70568 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
manage_sp_dashboard_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_4639 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
manage_sysadmin_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_2353 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
manage_stats_api_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_43262 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"

manage_prod_sp_dashboard_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_61697 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
spdashboard_symfony_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_82400 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
lifecycle_symfony_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_43297 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
lifecycle_api_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_86048 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
monitoring_oidc_client_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_52037 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
monitoring_tests_oidcng_client_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_32760 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
monitoring_tests_oidcng_resource_server_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_63433 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"

engineblock_private_keys:
default: |
  {{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_34678 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}

backend_tls_key: |
  {{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_24051 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}
iptables_incoming:
  - name: SSH
    port: 22


iptables6_incoming:
  - name: SSH
    port: 22

kibana_oidc_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_37485 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
kibana_oidc_crypto_passphrase: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_82806 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
logstash_ebauth_sha_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_17290 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
stats_api_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_75064 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
stats_dashboard_api_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_88334 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
stats_sysadmin_api_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_48024 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
stats_oidc_client_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_32183 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
stats_oidc_crypto_pass: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_55219 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"

dashboard_sab_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_63094 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
dashboard_sab_rest_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_9142 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
dashboard_sp_dashboard_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_74468 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
dashboard_jira_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_37171 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"

influxdb_admin_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_3153 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
influxdb_stats_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_55400 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"

oidcng_secure_secret:  "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_21549 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
oidcng_private_key: |
  {{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_86051 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}

oidcng_secret_keyset: |
  {
    "primaryKeyId": "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_76989 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
    "key": [
    {
      "keyData": {
        "typeUrl": "type.googleapis.com/google.crypto.tink.AesCtrHmacAeadKey",
        "keyMaterialType": ""{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_13470 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
        "value": ""{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_65341 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}""
      },
      "outputPrefixType": "TINK",
      "keyId": "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_19966 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"
      "status": "ENABLED"
    }
    ]
  }
oidcng_associated_data: 0B969613-89B9-4AC4-BC2F-363EFE1B21E7
oidcng_access_token_one_way_hash_salt: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_6421 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}"

myconext_private_key: |
  {{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_16973 token=hvs.VFfZyxeBFW7L0N9mPxqsQqcj url=http://127.0.0.1:8200')['password'] }}