env: vm
base_domain: "{{ env }}.openconext.org"

mysql_host: localhost
rsyslog_host: localhost

database_clients: [ "{{ mysql_host }}" ]

mysql_root_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_3645 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"

mysql_passwords:
  teams: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_51317 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
  eb: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_89301 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
  pdp_server: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_28058 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
  aa_server: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_48134 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
  spdashboard: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_14746 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
  shibboleth: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_23818 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
  lifecycle: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_80115 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"

mongo_passwords:
   manage: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_12455 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
   oidcng: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_46823 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
   myconext: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_68371 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"

mongo_admin_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_437 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"

engine_parameters_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_59446 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"

profile_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_74644 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"

teams_authz_client_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_20717 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
teams_migration_secret_key: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_59997 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"

engine_api_metadata_push_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_324 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
oidcng_api_metadata_push_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_65870 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
oidcng_api_tokens_profile_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_27751 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
oidcng_api_tokens_eduid_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_64457 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
myconext_api_attribute_manipulation_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_49625 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
myconext_oidcng_rs_client_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_15080 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
myconext_api_attribute_aggregation_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_93299 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
myconext_client_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_1538 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
myconext_rs_client_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_43252 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
engine_api_profile_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_43252 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
engine_api_deprovision_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_60366 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"

voot_oidcng_checkToken_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_61410 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"

external_group_provider_secrets:
  teams: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_22170 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"

teams_api_lifecycle_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_3419 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
attribute_aggregator_api_lifecycle_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_20198 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"

oidc_playground_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_51216 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
oidc_playground_jwt_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_13785 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
oidc_playground_resource_server_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_53600 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"

pdp_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_24462 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
pdp_client_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_29418 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
pdp_sab_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_38590 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"

aa_eb_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_43088 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
aa_authz_client_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_59650 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
aa_sab_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_40880 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
aa_idin_client_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_96422 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
aa_orcid_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_48615 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
aa_surfmarket_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_49168 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
aa_sbs_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_99308 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
aa_ala_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_26594 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
aa_manage_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_75437 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"

manage_pdp_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_75831 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"

attribute_aggregator_js_access_token: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_82143 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
pdp_js_access_token: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_31084 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"

https_star_private_key: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_70144 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"

mujina_idp_private_key: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_17291 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
mujina_idp_passphrase: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_56717 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
mujina_sp_private_key: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_78576 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
mujina_sp_passphrase: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_15936 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"

manage_internal_api_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_26726 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
manage_backdoor_api_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_90894 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
manage_dashboard_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_81302 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
manage_pdp_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_79757 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
manage_sp_dashboard_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_19921 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
manage_sysadmin_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_18684 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
manage_stats_api_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_19714 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"

manage_prod_sp_dashboard_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_84803 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
spdashboard_symfony_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_92685 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
lifecycle_symfony_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_43689 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
lifecycle_api_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_75435 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
monitoring_oidc_client_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_79484 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
monitoring_tests_oidcng_client_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_86856 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
monitoring_tests_oidcng_resource_server_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_49780 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"

engineblock_private_keys:
default: |
  {{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_1270 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}

backend_tls_key: |
  {{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_71547 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}
iptables_incoming:
  - name: SSH
    port: 22


iptables6_incoming:
  - name: SSH
    port: 22

kibana_oidc_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_63929 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
kibana_oidc_crypto_passphrase: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_65977 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
logstash_ebauth_sha_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_16745 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
stats_api_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_74390 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
stats_dashboard_api_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_18528 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
stats_sysadmin_api_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_86650 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
stats_oidc_client_secret: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_1795 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
stats_oidc_crypto_pass: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_27291 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"

dashboard_sab_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_98748 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
dashboard_sab_rest_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_89679 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
dashboard_sp_dashboard_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_66475 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
dashboard_jira_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_39585 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"

influxdb_admin_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_24580 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
influxdb_stats_password: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_42536 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"

oidcng_secure_secret:  "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_21423 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
oidcng_private_key: |
  {{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_59730 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}

oidcng_secret_keyset: |
  {
    "primaryKeyId": "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_33115 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
    "key": [
    {
      "keyData": {
        "typeUrl": "type.googleapis.com/google.crypto.tink.AesCtrHmacAeadKey",
        "keyMaterialType": ""{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_76964 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
        "value": ""{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_35061 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}""
      },
      "outputPrefixType": "TINK",
      "keyId": "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_1296 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"
      "status": "ENABLED"
    }
    ]
  }
oidcng_associated_data: 0B969613-89B9-4AC4-BC2F-363EFE1B21E7
oidcng_access_token_one_way_hash_salt: "{{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_96248 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}"

myconext_private_key: |
  {{ lookup('hashi_vault', 'secret=secret/data/SECRET_PATH_16897 token=hvs.9NlDVBH6boIb05GGpE4g6JBJ url=http://127.0.0.1:8200')['password'] }}